
import re
import pytest

from playwright.sync_api import (
    Page,
    expect,
    BrowserContext
)


@pytest.fixture
def base_url():
    return "https://ideabytes.com"


# Generated Tests

# ==========================================
# AUTO GENERATED BY AI PLAYWRIGHT GENERATOR
# ==========================================


# Test Case 1

# =====================================================
# TC001 - Verify homepage loads with expected title
# =====================================================

def test_verify_homepage_loads_with_expected_title(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')



# Test Case 2

# =====================================================
# TC002 - Click Contact link and verify navigation to contact page
# =====================================================

def test_click_contact_link_and_verify_navigation_to_contact_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Click the 'Contact' link using selector a:has-text('Contact')")
    # Unsupported Step: Click the 'Contact' link using selector a:has-text('Contact')



# Test Case 3

# =====================================================
# TC003 - Click IoT Solutions link and verify external URL opens
# =====================================================

def test_click_iot_solutions_link_and_verify_external_url_opens(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Click the 'IoT Solutions' link using selector a:has-text('IoT Solutions')")
    # Unsupported Step: Click the 'IoT Solutions' link using selector a:has-text('IoT Solutions')

    expect(page).to_have_url("https://www.ideabytesiot.com/")


# Test Case 4

# =====================================================
# TC004 - Click Test Automation link and verify navigation to test-automation page
# =====================================================

def test_click_test_automation_link_and_verify_navigation_to_test_automation_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Click the 'Test Automation' link using selector a:has-text('Test Automation')")
    # Unsupported Step: Click the 'Test Automation' link using selector a:has-text('Test Automation')



# Test Case 5

# =====================================================
# TC005 - Click Teens4Tech link and verify navigation to Teens_tech page
# =====================================================

def test_click_teens4tech_link_and_verify_navigation_to_teens_tech_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Click the 'Teens4Tech' link using selector a:has-text('Teens4Tech')")
    # Unsupported Step: Click the 'Teens4Tech' link using selector a:has-text('Teens4Tech')



# Test Case 6

# =====================================================
# TC006 - Fill Teens_tech registration form with valid data and submit
# =====================================================

def test_fill_teens_tech_registration_form_with_valid_data_and_submit(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/Teens_tech.html")
    page.wait_for_load_state('networkidle')
    page.fill("the name input (name='widget-contact-form-name')", "John Doe")
    page.fill("the email input (name='widget-contact-form-email')", "john@example.com")
    page.fill("the age input (name='widget-contact-form-company')", "15")
    print("WARNING: Unsupported step -> Click the Register button using selector")
    # Unsupported Step: Click the Register button using selector



# Test Case 7

# =====================================================
# TC007 - Submit empty Teens_tech registration form and verify validation errors
# =====================================================

def test_submit_empty_teens_tech_registration_form_and_verify_validation_errors(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/Teens_tech.html")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Click the Register button using selector")
    # Unsupported Step: Click the Register button using selector



# Test Case 8

# =====================================================
# TC008 - Fill only name field on Teens_tech form and verify email validation
# =====================================================

def test_fill_only_name_field_on_teens_tech_form_and_verify_email_validation(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/Teens_tech.html")
    page.wait_for_load_state('networkidle')
    page.fill("the name input (name='widget-contact-form-name')", "John Doe")
    print("WARNING: Unsupported step -> Click the Register button using selector")
    # Unsupported Step: Click the Register button using selector



# Test Case 9

# =====================================================
# TC009 - Verify name input placeholder on Teens_tech page
# =====================================================

def test_verify_name_input_placeholder_on_teens_tech_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/Teens_tech.html")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Check placeholder attribute of input[name='widget-contact-form-name']")
    # Unsupported Step: Check placeholder attribute of input[name='widget-contact-form-name']



# Test Case 10

# =====================================================
# TC010 - Verify email input type attribute on Teens_tech page
# =====================================================

def test_verify_email_input_type_attribute_on_teens_tech_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/Teens_tech.html")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Check type attribute of input[name='widget-contact-form-email']")
    # Unsupported Step: Check type attribute of input[name='widget-contact-form-email']



# Test Case 11

# =====================================================
# TC011 - Verify age input placeholder on Teens_tech page
# =====================================================

def test_verify_age_input_placeholder_on_teens_tech_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/Teens_tech.html")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Check placeholder attribute of input[name='widget-contact-form-company']")
    # Unsupported Step: Check placeholder attribute of input[name='widget-contact-form-company']



# Test Case 12

# =====================================================
# TC012 - Verify PDF document loads successfully
# =====================================================

def test_verify_pdf_document_loads_successfully(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/certificates/Ideabytes-ISO-IEC27017-2015.pdf")
    page.wait_for_load_state('networkidle')



# Test Case 13

# =====================================================
# TC013 - Verify LinkedIn link is present and clickable on homepage
# =====================================================

def test_verify_linkedin_link_is_present_and_clickable_on_homepage(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Locate the LinkedIn link using selector a[href='https://in.linkedin.com/company/ideabytes-inc']")
    # Unsupported Step: Locate the LinkedIn link using selector a[href='https://in.linkedin.com/company/ideabytes-inc']



# Test Case 14

# =====================================================
# TC014 - Verify logo link is present and visible on homepage
# =====================================================

def test_verify_logo_link_is_present_and_visible_on_homepage(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Locate the logo link using selector a[href='https://ideabytes.com/index.html']")
    # Unsupported Step: Locate the logo link using selector a[href='https://ideabytes.com/index.html']



# Test Case 15

# =====================================================
# TC015 - Verify about-us page loads successfully
# =====================================================

def test_verify_about_us_page_loads_successfully(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/about-us.html")
    page.wait_for_load_state('networkidle')



# Test Case 16

# =====================================================
# TC016 - Verify team page loads successfully
# =====================================================

def test_verify_team_page_loads_successfully(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/team.html")
    page.wait_for_load_state('networkidle')



# Test Case 17

# =====================================================
# TC017 - Verify Register button is visible and enabled on Teens_tech page
# =====================================================

def test_verify_register_button_is_visible_and_enabled_on_teens_tech_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/Teens_tech.html")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Locate the Register button using selector")
    # Unsupported Step: Locate the Register button using selector



# Test Case 18

# =====================================================
# TC018 - Click Application Development link and verify navigation to web-mobile-app-dev page
# =====================================================

def test_click_application_development_link_and_verify_navigation_to_web_mobile_app_dev_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Click the 'Application Development' link using selector a:has-text('Application Development')")
    # Unsupported Step: Click the 'Application Development' link using selector a:has-text('Application Development')



# Test Case 19

# =====================================================
# TC019 - Click DG HAZMAT link and verify external URL opens
# =====================================================

def test_click_dg_hazmat_link_and_verify_external_url_opens(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Click the 'DG HAZMAT' link using selector a:has-text('DG HAZMAT')")
    # Unsupported Step: Click the 'DG HAZMAT' link using selector a:has-text('DG HAZMAT')

    expect(page).to_have_url("https://www.dgsms.ca")


# Test Case 20

# =====================================================
# TC020 - Click IGBMS link and verify external URL opens
# =====================================================

def test_click_igbms_link_and_verify_external_url_opens(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Click the 'IGBMS' link using selector a:has-text('IGBMS')")
    # Unsupported Step: Click the 'IGBMS' link using selector a:has-text('IGBMS')

    expect(page).to_have_url("https://igbms.com/")

