
import re
import pytest

from playwright.sync_api import (
    Page,
    expect,
    BrowserContext
)


@pytest.fixture
def base_url():
    return "https://ideabytes.com"


# Generated Tests

# ==========================================
# AUTO GENERATED BY AI PLAYWRIGHT GENERATOR
# ==========================================


# Test Case 1

# =====================================================
# TC001 - Verify homepage title contains Ideabytes
# =====================================================

def test_verify_homepage_title_contains_ideabytes(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    expect(page).to_have_title(re.compile("Ideabytes"))

    expect(page).to_have_title(re.compile("the text 'Ideabytes"))


# Test Case 2

# =====================================================
# TC002 - Navigate to Contact page via link
# =====================================================

def test_navigate_to_contact_page_via_link(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a:has-text('Contact')")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')

    expect(page).to_have_url("https://ideabytes.com/contact-us.html")


# Test Case 3

# =====================================================
# TC003 - Navigate to Test Automation page via link
# =====================================================

def test_navigate_to_test_automation_page_via_link(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a:has-text('Test Automation')")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')

    expect(page).to_have_url("https://ideabytes.com/test-automation.html")


# Test Case 4

# =====================================================
# TC004 - Navigate to Application Development page via link
# =====================================================

def test_navigate_to_application_development_page_via_link(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a:has-text('Application Development')")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')

    expect(page).to_have_url("https://ideabytes.com/web-mobile-app-dev.html")


# Test Case 5

# =====================================================
# TC005 - Navigate to Teens4Tech page via link
# =====================================================

def test_navigate_to_teens4tech_page_via_link(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a:has-text('Teens4Tech')")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')

    expect(page).to_have_url("https://ideabytes.com/Teens_tech.html")


# Test Case 6

# =====================================================
# TC006 - Navigate to Partnerships page via link
# =====================================================

def test_navigate_to_partnerships_page_via_link(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a:has-text('Partnerships')")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')

    expect(page).to_have_url("https://ideabytes.com/partnership.html")


# Test Case 7

# =====================================================
# TC007 - Navigate to IoT Solutions external site
# =====================================================

def test_navigate_to_iot_solutions_external_site(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a:has-text('IoT Solutions')")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')

    expect(page).to_have_url("https://www.ideabytesiot.com/")


# Test Case 8

# =====================================================
# TC008 - Navigate to DG HAZMAT external site
# =====================================================

def test_navigate_to_dg_hazmat_external_site(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a:has-text('DG HAZMAT')")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')

    expect(page).to_have_url("https://www.dgsms.ca")


# Test Case 9

# =====================================================
# TC009 - Navigate to IGBMS external site
# =====================================================

def test_navigate_to_igbms_external_site(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a:has-text('IGBMS')")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')

    expect(page).to_have_url("https://igbms.com/")


# Test Case 10

# =====================================================
# TC010 - Navigate to LinkedIn page via link
# =====================================================

def test_navigate_to_linkedin_page_via_link(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.click("a[href='https://in.linkedin.com/company/ideabytes-inc']")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')



# Test Case 11

# =====================================================
# TC011 - Mobile menu hamburger toggle on 375x667 viewport
# =====================================================

def test_mobile_menu_hamburger_toggle_on_375x667_viewport(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    page.set_viewport_size({'width': 375, 'height': 667})
    print("WARNING: Unsupported step -> Click the button with selector \"button:has-text('')\"")
    # Unsupported Step: Click the button with selector "button:has-text('')"
    page.wait_for_load_state('networkidle')



# Test Case 12

# =====================================================
# TC012 - Verify security testing article page loads successfully
# =====================================================

def test_verify_security_testing_article_page_loads_successfully(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/security-testing-article-2.html")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')
    expect(page.locator("body")).to_contain_text("404")



# Test Case 13

# =====================================================
# TC013 - Verify certificates page contains Certificates heading
# =====================================================

def test_verify_certificates_page_contains_certificates_heading(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/certificates.html")
    page.wait_for_load_state('networkidle')
    expect(page.locator("h1")).to_be_visible()

    expect(page.locator("h1")).to_be_visible()


# Test Case 14

# =====================================================
# TC014 - Check homepage button for accessible name (aria-label)
# =====================================================

def test_check_homepage_button_for_accessible_name_aria_label(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com")
    page.wait_for_load_state('networkidle')
    print("WARNING: Unsupported step -> Locate button with selector \"button:has-text('')\"")
    # Unsupported Step: Locate button with selector "button:has-text('')"
    print("WARNING: Unsupported step -> Retrieve its accessible name attribute (aria-label)")
    # Unsupported Step: Retrieve its accessible name attribute (aria-label)
    print("WARNING: Unsupported step -> If accessible name is empty or missing, report accessibility issue")
    # Unsupported Step: If accessible name is empty or missing, report accessibility issue

    # TODO: Accessibility validation


# Test Case 15

# =====================================================
# TC015 - Verify 404 on non-existent page
# =====================================================

def test_verify_404_on_non_existent_page(page: Page):
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(30000)

    page.goto("https://ideabytes.com/nonexistent")
    page.wait_for_load_state('networkidle')
    page.wait_for_load_state('networkidle')
    expect(page.locator("body")).to_contain_text("404")


