from agents.state import AgentState


def code_gen_agent(state: AgentState) -> AgentState:
    print("[Code Generation Agent] Running...")

    state["generated_code"] = """
    # Placeholder code generated by the agent
    def test_login():
        pass
    """

    print("[Code Generation Agent] Code generated.")
    return state