from pathlib import Path
import os
import re
import py_compile

from agents.state import AgentState
from agents.llm_client import get_llm
from performance.engine import PerformanceTracker

from agents.prompts.yaml_prompt import YAML_PROMPT
from agents.python_fallback import generate_python_directly

from app.yaml_validator import validate_yaml
from app.yaml_to_playwright import convert_yaml_to_playwright

from agents.selector_utils import cap_selectors
from test_runner import ast_safety_check


llm = get_llm()


def verify_generated_code(filepath: str) -> bool:
    """
    Verify that the generated Python code is syntactically valid.
    """
    try:
        py_compile.compile(filepath, doraise=True)
        print(f"[Code Gen] Syntax check PASSED: {filepath}")
        return True

    except py_compile.PyCompileError as e:
        print(f"[Code Gen] Syntax check FAILED:\n{e}")
        return False


def generate_conftest(output_dir: Path) -> None:
    """
    Write a conftest.py with browser fixture next to the generated test.
    """
    base_url = os.getenv("BASE_URL", "http://localhost:3000")

    content = f'''"""
Auto-generated conftest.py — do not edit manually.
Generated by code_gen_agent alongside generated_test.py.
"""
import pytest
from playwright.sync_api import sync_playwright, Browser, Page

BASE_URL = "{base_url}"


@pytest.fixture(scope="session")
def browser():
    """Session-scoped Playwright browser fixture."""
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        yield browser
        browser.close()


@pytest.fixture
def page(browser: Browser) -> Page:
    """Function-scoped page with BASE_URL pre-set."""
    context = browser.new_context(base_url=BASE_URL)
    page = context.new_page()
    yield page
    context.close()
'''
    path = output_dir / "conftest.py"

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[Code Gen] conftest.py written to {path}")


def check_assertions(filepath: str) -> bool:
    """
    Warn if generated test functions have no expect() assertions.
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        test_fns = re.findall(r"def (test_\w+)", content)
        expect_count = content.count("expect(")

        if test_fns and expect_count == 0:
            print(
                f"[Code Gen] WARNING: {len(test_fns)} test function(s) "
                "found but ZERO expect() assertions."
            )
            return False

        print(
            f"[Code Gen] Assertion check OK: "
            f"{expect_count} expect() call(s) found."
        )
        return True

    except Exception as e:
        print(f"[Code Gen] Assertion check error: {e}")
        return False
    
    

# Inside code_gen_agent(), add after verify_generated_code():
# check_assertions(str(output_path))




def code_gen_agent(state: AgentState) -> AgentState:
    tracker = PerformanceTracker(label="code_gen_agent")
    tracker.start()

    try:
        print("[Code Gen Agent] Running...")

        if state.get("regen_count", 0) > 0:
            print(
                f"[Code Gen Agent] Regeneration Pass #{state['regen_count']}"
            )

        selectors = state.get("selectors", [])

        buttons = cap_selectors(
            [s for s in selectors if s.get("type") == "button"],
            "buttons",
        )

        inputs = cap_selectors(
            [s for s in selectors if s.get("type") == "input"],
            "inputs",
        )

        links = cap_selectors(
            [s for s in selectors if s.get("type") == "link"],
            "links",
        )

        review_notes = state.get("review_notes", "")
        regen_prefix = ""

        if state.get("needs_regen") and review_notes:
            regen_prefix = (
                "PREVIOUS REVIEW FEEDBACK\n"
                "Fix these issues before generating again:\n\n"
                f"{review_notes}\n\n"
            )

        yaml_prompt = YAML_PROMPT.format(
            task_plan=regen_prefix + "\n".join(state.get("task_plan", [])),
            architecture_notes=state.get("architecture_notes", ""),
            buttons=buttons,
            inputs=inputs,
            links=links,
        )

        # -------------------------------------------------
        # Generate YAML
        # -------------------------------------------------

        yaml_response = llm.invoke(yaml_prompt)

        yaml_text = (
            yaml_response.content
            if hasattr(yaml_response, "content")
            else str(yaml_response)
        )
        
        
        print("\n" + "=" * 80)
        print("GENERATED YAML")
        print("=" * 80)
        print(yaml_text)
        print("=" * 80 + "\n")

        validation = validate_yaml(yaml_text)

        state["yaml_validation"] = validation

        print(f"[Code Gen] YAML valid: {validation['valid']}")

        # -------------------------------------------------
        # Keep the last valid YAML
        # -------------------------------------------------

        if validation["valid"]:
            state["generated_yaml"] = yaml_text
            state["best_yaml"] = yaml_text

        elif state.get("best_yaml"):
            print("[Code Gen] Reusing previous valid YAML.")
            yaml_text = state["best_yaml"]

        # -------------------------------------------------
        # Generate Playwright Code
        # -------------------------------------------------

        if validation["valid"] or state.get("best_yaml"):

            playwright = convert_yaml_to_playwright(yaml_text)

            code = playwright.get("code", "")

            unsupported = playwright.get(
                "unsupported_steps",
                [],
            )

            print(
                f"[Code Gen] Unsupported Steps: {len(unsupported)}"
            )

        else:

            print(
                "[Code Gen] Falling back to direct Python generation..."
            )

            code = generate_python_directly(
                state,
                llm,
            )
            
            

        # -------------------------------------------------
        # Save Generated Code
        # -------------------------------------------------

        state["generated_code"] = code

        output_dir = Path("generated_tests")
        output_dir.mkdir(exist_ok=True)

        # Generate conftest.py only after ensuring the directory exists
        generate_conftest(output_dir)

        output_path = output_dir / "generated_test.py"

        output_path.write_text(
            code,
            encoding="utf-8",
        )

        print(f"[Code Gen] Script saved to {output_path}")

        # -------------------------------------------------
        # Validate Generated Code
        # -------------------------------------------------

        syntax_ok = verify_generated_code(str(output_path))
        state["syntax_passed"] = syntax_ok

        if syntax_ok:

            # -----------------------------
            # AST Safety Check
            # -----------------------------
            is_safe, reason = ast_safety_check(str(output_path))

            if not is_safe:

                print(f"[Code Gen] SAFETY BLOCK: {reason}")

                state["needs_regen"] = True
                state["syntax_passed"] = False

                if state.get("best_code"):
                    state["generated_code"] = state["best_code"]

            else:

                # -----------------------------
                # Assertion Check
                # -----------------------------
                assertions_ok = check_assertions(str(output_path))

                state["assertions_passed"] = assertions_ok

                state["best_code"] = code
                state["needs_regen"] = False

                print("[Code Gen] Best generated code updated.")

        else:

            print(
                "[Code Gen] Syntax failed. Keeping previous best code."
            )

            if state.get("best_code"):
                state["generated_code"] = state["best_code"]

            state["needs_regen"] = True

    except Exception as e:

        print(f"[Code Gen Error] {e}")

        state["generated_code"] = state.get("best_code", "")
        state["generated_yaml"] = state.get("best_yaml", "")
        

        state["yaml_validation"] = {
            "valid": False,
            "errors": [str(e)],
        }

        state["syntax_passed"] = False
        state["assertions_passed"] = False
        state["needs_regen"] = True

    finally:

        tracker.stop(agents_completed=1)
        tracker.save("reports/per_agent_perf.json")

    return state