from pathlib import Path
import os
import re
import py_compile

from agents.state import AgentState
from agents.llm_client import get_llm
from performance.engine import PerformanceTracker

from agents.prompts.yaml_prompt import (
    YAML_PROMPT,
    LIVE_DATA_INSTRUCTIONS,
)
from agents.python_fallback import generate_python_directly

from app.yaml_validator import validate_yaml
from app.yaml_to_playwright import convert_yaml_to_playwright

from agents.selector_utils import cap_selectors
from test_runner import ast_safety_check

SPA_WAIT_TIMEOUT = int(
    os.getenv("SPA_WAIT_TIMEOUT", "15000")
)
def strip_markdown_code_fences(code: str) -> str:
    """
    Remove Markdown code fences from LLM output.
    """
    code = code.strip()

    if code.startswith("```python"):
        code = code[len("```python"):]

    elif code.startswith("```"):
        code = code[len("```"):]

    if code.endswith("```"):
        code = code[:-3]

    return code.strip()

def verify_generated_code(filepath: str) -> bool:
    """
    Verify that the generated Python code is syntactically valid.
    """
    try:
        py_compile.compile(filepath, doraise=True)
        print(f"[Code Gen] Syntax check PASSED: {filepath}")
        return True

    except py_compile.PyCompileError as e:
        print(f"[Code Gen] Syntax check FAILED:\n{e}")
        return False



CONFTEST_SPA_HELPERS = '''

def wait_for_widget(page: Page, selector: str, timeout: int = 15000):
    """
    Wait until an IoT widget has completely rendered.
    """

    page.wait_for_selector(
    selector,
    state="visible",
    timeout=timeout,
    )


    # Optional loading indicators
    try:
        page.wait_for_selector(
            ".loading, .spinner, [data-loading='true']",
            state="hidden",
            timeout=5000,
        )
    except Exception:
        pass


def wait_for_live_data(page: Page, timeout: int = 10000):
    page.wait_for_load_state("domcontentloaded")

    try:
        page.wait_for_selector(
            "ib-iot-root",
            timeout=timeout,
        )
    except Exception:
        pass

    page.wait_for_timeout(500)

'''

def generate_conftest(output_dir: Path) -> None:
    """
    Write a conftest.py with browser fixture next to the generated test.
    """
    base_url = os.getenv(
        "BASE_URL",
        "https://live.ideabytesiot.com/demolive",
    )

    content = f'''"""
Auto-generated conftest.py — do not edit manually.
Generated by code_gen_agent alongside generated_test.py.
"""
import os
import pytest
from playwright.sync_api import sync_playwright, Browser, Page

BASE_URL = "{base_url}"


SPA_WAIT_TIMEOUT = int(
    os.getenv("SPA_WAIT_TIMEOUT", "15000")
)


@pytest.fixture(scope="session")
def browser():
    """Session-scoped Playwright browser fixture."""
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        yield browser
        browser.close()

@pytest.fixture(scope="session")
def base_url():
    """
    Expose BASE_URL as a pytest fixture so generated tests can
    request `base_url` as a parameter.
    """
    return BASE_URL
    
    

@pytest.fixture
def page(browser):

    if os.path.exists("auth.json"):

        ctx = browser.new_context(
            storage_state="auth.json",
        )

    else:

        ctx = browser.new_context(
            base_url=BASE_URL,
        )

    page = ctx.new_page()

    page.set_default_timeout(SPA_WAIT_TIMEOUT)
    page.set_default_navigation_timeout(30000)

    # Prime the authenticated session
    page.goto(
        "https://live.ideabytesiot.com/demolive/dashboard/status-list"
    )

    page.wait_for_load_state("domcontentloaded")

    try:
        page.wait_for_selector(
            "ib-iot-root",
            timeout=SPA_WAIT_TIMEOUT,
        )
    except Exception:
        pass

    yield page

    ctx.close()
    

'''
    content += CONFTEST_SPA_HELPERS

    path = output_dir / "conftest.py"

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[Code Gen] conftest.py written to {path}")


def check_assertions(filepath: str) -> bool:
    """
    Warn if generated test functions have no expect() assertions.
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        test_fns = re.findall(r"def (test_\w+)", content)
        expect_count = content.count("expect(")

        if test_fns and expect_count == 0:
            print(
                f"[Code Gen] WARNING: {len(test_fns)} test function(s) "
                "found but ZERO expect() assertions."
            )
            return False

        print(
            f"[Code Gen] Assertion check OK: "
            f"{expect_count} expect() call(s) found."
        )
        return True

    except Exception as e:
        print(f"[Code Gen] Assertion check error: {e}")
        return False
    

def code_gen_agent(state: AgentState) -> AgentState:
    tracker = PerformanceTracker(label="code_gen_agent")
    tracker.start()

    try:
        llm = get_llm()
        print("[Code Gen Agent] Running...")
        print(
            f"[Code Gen Agent] regen_count={state.get('regen_count', 0)} "
            f"needs_regen={state.get('needs_regen', False)}"
        )

        # Single source of truth for regen counting — bump the counter when
        # re-entering because a previous review/safety/syntax check asked
        # for regeneration. Without this, regen_count stays 0 forever.
        if state.get("needs_regen", False):
            state["regen_count"] = state.get("regen_count", 0) + 1
            print(
                f"[Code Gen Agent] Regeneration Pass #{state['regen_count']}"
            )

        selectors = state.get("selectors", [])

        buttons = cap_selectors(
            [s for s in selectors if s.get("type") == "button"],
            "buttons",
        )

        inputs = cap_selectors(
            [s for s in selectors if s.get("type") == "input"],
            "inputs",
        )

        links = cap_selectors(
            [s for s in selectors if s.get("type") == "link"],
            "links",
        )

        review_notes = state.get("review_notes", "")
        regen_prefix = ""

        if state.get("needs_regen") and review_notes:
            regen_prefix = f"""
            PREVIOUS REVIEW FEEDBACK

            The previous Playwright generation FAILED review.

            You MUST fix every issue below.

            {review_notes}

            IMPORTANT

            - Do NOT generate expect_page() unless a popup is explicitly opened.
            - Use page.goto() for normal navigation.
            - Convert every Fill step into page.fill().
            - Convert every Click step into page.click().
            - Use detected selectors only.
            - Do not invent selectors.
            - Every test must contain at least one expect().
            - Use wait_for_live_data(page) after navigation.
            - Use wait_for_widget(page, selector) before interacting with dynamic widgets.
            """

        yaml_prompt = YAML_PROMPT.format(
            live_data_instructions=LIVE_DATA_INSTRUCTIONS,
            target_url=state.get("target_url", ""),
            task_plan=regen_prefix + "\n".join(state.get("task_plan", [])),
            architecture_notes=state.get("architecture_notes", ""),
            buttons=buttons,
            inputs=inputs,
            links=links,
        )
        

        # -------------------------------------------------
        # Generate YAML
        # -------------------------------------------------

        yaml_response = llm.invoke(yaml_prompt)

        yaml_text = (
            yaml_response.content
            if hasattr(yaml_response, "content")
            else str(yaml_response)
        )
        
        
        print("\n" + "=" * 80)
        print("GENERATED YAML")
        print("=" * 80)
        print(yaml_text)
        print("=" * 80 + "\n")

        validation = validate_yaml(yaml_text)

        state["yaml_validation"] = validation

        print(f"[Code Gen] YAML valid: {validation['valid']}")

        # -------------------------------------------------
        # Keep the last valid YAML
        # -------------------------------------------------

        if validation["valid"]:
            state["generated_yaml"] = yaml_text
            state["best_yaml"] = yaml_text

        elif state.get("best_yaml"):
            print("[Code Gen] Reusing previous valid YAML.")
            yaml_text = state["best_yaml"]

        # -------------------------------------------------
        # Generate Playwright Code
        # -------------------------------------------------

        if validation["valid"] or state.get("best_yaml"):

            playwright = convert_yaml_to_playwright(yaml_text)

            code = playwright.get("code", "")
            code = strip_markdown_code_fences(code)
            if "expect_page(" in code and "popup" not in code.lower():
                print("[Code Gen] Invalid expect_page() detected.")
                state["needs_regen"] = True
            previous_code = state.get("best_code", "")

            if previous_code and code == previous_code:
                print("[Code Gen] Generated code identical to previous attempt.")
                state["duplicate_generation"] = True
            else:
                state["duplicate_generation"] = False
            if not code.strip():
                raise ValueError("YAML conversion returned empty Playwright code.")

            unsupported = playwright.get(
                "unsupported_steps",
                [],
            )

            print(
            f"[Code Gen] Unsupported Steps: {len(unsupported)}"
        )

        if unsupported:
            print("[Code Gen] Unsupported Playwright steps detected:")
            for step in unsupported:
                print("  -", step)

            state["needs_regen"] = True

        else:

            print(
                "[Code Gen] Falling back to direct Python generation..."
            )

            code = generate_python_directly(
                state,
                llm,
            )
            if not code.strip():
                raise ValueError("Python fallback returned empty code.")
            
            

        # -------------------------------------------------
        # Save Generated Code
        # -------------------------------------------------

        state["generated_code"] = code

        output_dir = Path("generated_tests")
        output_dir.mkdir(exist_ok=True)

        # Generate conftest.py only after ensuring the directory exists
        conftest_path = output_dir / "conftest.py"

        
        generate_conftest(output_dir)

        output_path = output_dir / "generated_test.py"

        output_path.write_text(
            code,
            encoding="utf-8",
        )

        print(f"[Code Gen] Script saved to {output_path}")

        # -------------------------------------------------
        # Validate Generated Code
        # -------------------------------------------------

        syntax_ok = verify_generated_code(str(output_path))
        state["syntax_passed"] = syntax_ok

        if syntax_ok:

            # -----------------------------
            # AST Safety Check
            # -----------------------------
            is_safe, reason = ast_safety_check(str(output_path))

            if not is_safe:

                print(f"[Code Gen] SAFETY BLOCK: {reason}")

                state["needs_regen"] = True
                state["syntax_passed"] = False

                if state.get("best_code"):
                    state["generated_code"] = state["best_code"]

            else:

                # -----------------------------
                # Assertion Check
                # -----------------------------
                assertions_ok = check_assertions(str(output_path))
                
                
                
                weak_patterns = [
                    'expect(page.locator("body"))',
                    "expect(page).to_have_url",
                ]

                generated = output_path.read_text(encoding="utf-8")
                
                invalid_patterns = [
                    "input[name='']",
                    'input[name=""]',
                    "input[id='']",
                    'input[id=""]',
                    "button:has-text('')",
                    'button:has-text("")',
                    "a:has-text('')",
                    'a:has-text("")',
                ]
                
                invalid_patterns.extend([
                    "#temperature-widget",
                    "#humidity-widget",
                    "#sensor-widget",
                    "#chart-widget",
                    ".dashboard-card",
                    ".device-list",
                    "Assuming a temperature widget",
                    "generic selector",
                ])

                for pattern in invalid_patterns:
                    if pattern in generated:
                        print(f"[Code Gen] Invalid selector detected: {pattern}")
                        assertions_ok = False
                                
                
                
                forbidden_selectors = [
                    ".dashboard-card",
                    ".temperature-widget",
                    ".humidity-widget",
                    ".device-list",
                    ".filter",
                ]

                for selector in forbidden_selectors:
                    if selector in generated:
                        print(f"[Code Gen] Invented selector detected: {selector}")
                        assertions_ok = False

                if generated.count('page.fill("#username"') > 1:
                    print("[Code Gen] Duplicate login flow detected.")
                    assertions_ok = False

                if "Demo@123" in generated or "demo@ideabytesiot.com" in generated:
                    print("[Code Gen] Hardcoded credentials detected.")
                    assertions_ok = False
                

                for pattern in weak_patterns:
                    if pattern in generated:
                        print(f"[Code Gen] Weak assertion detected: {pattern}")
                        assertions_ok = False
                                
                
                
                state["assertions_passed"] = assertions_ok

                if assertions_ok:

                    state["best_code"] = code
                    state["needs_regen"] = False

                    print("[Code Gen] Best generated code updated.")

                else:

                    print(
                        "[Code Gen] Generated test contains no assertions. "
                        "Requesting regeneration."
                    )

                    state["needs_regen"] = True

                    if state.get("best_code"):
                        state["generated_code"] = state["best_code"]

        else:

            print(
                "[Code Gen] Syntax failed. Keeping previous best code."
            )

            if state.get("best_code"):
                state["generated_code"] = state["best_code"]

            state["needs_regen"] = True

    except Exception as e:

        print(f"[Code Gen Error] {e}")

        state["generated_code"] = state.get("best_code", "")
        state["generated_yaml"] = state.get("best_yaml", "")
        

        state["yaml_validation"] = {
            "valid": False,
            "errors": [str(e)],
        }

        state["syntax_passed"] = False
        state["assertions_passed"] = False
        state["needs_regen"] = True

    finally:

        tracker.stop(agents_completed=1)
        tracker.save("reports/per_agent_perf.json")

    return state